development:
  sessions:
    default:

      database: nested_mongoid_development

      hosts:
        - localhost:27017
      options:

  options:
    
test:
  sessions:
    default:
      database: nested_mongoid_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

        max_retries: 1
        retry_interval: 0
